version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    # - exhaustive
    - forcetypeassert
    - goconst
    # - godot
    # - godox
    - gomoddirectives
    - goprintffuncname
    # - gosec
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - perfsprint
    # - wrapcheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
