# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

metadata:
  maintainers:
    - "Stanislav (Stas) Katkov <devtui@skatkov.com>"
  homepage: "https://devtui.com"
  description: "A Swiss-army knife TUI for developers"
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - git push --tags

builds:
  - id: darwin
    env: ["CGO_ENABLED=1"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    ldflags:
      [
        "-s -w -X github.com/skatkov/devtui/cmd.version={{.Version}} -X github.com/skatkov/devtui/cmd.commit={{.Commit}} -X github.com/skatkov/devtui/cmd.date={{ .CommitDate }}",
      ]
    goos:
      - darwin
    binary: devtui

  - id: linux
    env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    ldflags:
      [
        "-s -w -X github.com/skatkov/devtui/cmd.version={{.Version}} -X github.com/skatkov/devtui/cmd.commit={{.Commit}} -X github.com/skatkov/devtui/cmd.date={{ .CommitDate }}",
      ]
    goos:
      - linux
    binary: devtui
changelog:
  sort: asc
  use: github
  format: '{{ replace (replace .Message "feat: " "") "fix: " "" }}'
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      devtui_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    # format_overrides:
    # - goos: windows
    #   format: zip
snapshot:
  version_template: "{{ incpatch .Version }}-next"

source:
  enabled: false

release:
  github:
    owner: skatkov
    name: homebrew-tap
  tag: "devtui-{{ .Tag }}"
  name_template: "devtui-{{ .Tag }}"
brews:
  - description: "A Swiss Army knife for developers"
    name: devtui
    url_template: "https://github.com/skatkov/homebrew-tap/releases/download/devtui-{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: skatkov
      name: homebrew-tap
